config/routes.rb
Rails.application.routes.draw do
  root "front_pages#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  resources :subboards, path: "s", only: [:new, :create, :show]
end

app/models/subboard.rb
class Subboard < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  after_create :generate_slug
  before_update :assign_slug

  def to_param
    slug
  end

  private

  def assign_slug
    self.slug = to_slug
  end

  def generate_slug
    update_attributes(slug: to_slug)
  end

  def to_slug
    name.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  before_filter :require_login
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/front_pages_controller.rb
class FrontPagesController < ApplicationController
  skip_before_filter :require_login
  def show

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/subboards_controller.rb
class SubboardsController < ApplicationController
  def new
    @subboard = Subboard.new
  end

  def create
    subboard = Subboard.new(subboard_params)
    subboard.save
    redirect_to subboard
  end

  def show
    @subboard = find_subboard
  end

  private

  def find_subboard
    Subboard.find_by(slug: params[:id])
  end

  def subboard_params
    params.require(:subboard).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_sign_in_form.html.haml
= form_for :session, url: session_path do |form|
  %div
    = form.label :email
    = form.email_field :email
  %div
    = form.label :password
    = form.password_field :password
  %div
    = form.submit "Sign in"

app/views/application/_sign_up_form.html.haml
= form_for @user do |form|
  - if @user.errors.any?
    = pluralize(@user.errors.count, "error")
      prevented your account from being created:
    %ul
    - @user.errors.full_messages.each do |error_message|
    %li= error_message
  %div
    = form.label :email
    = form.email_field :email
  %div
    = form.label :password
    = form.password_field :password
  %div
    = form.submit "Sign up"

app/views/front_pages/show.html.haml
= link_to "New Subboard", new_subboard_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Postr
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if signed_in?
      = current_user.email
      = link_to "Sign Out", session_path, method: :delete
    - else
      = link_to "Sign Up", new_user_path
      = link_to "Sign In", new_session_path

    = yield

app/views/subboards/new.html.haml
= form_for @subboard do |form|
  .title_form
    = form.label :name
    = form.text_field :name
  .description_form
    = form.label :description
    = form.text_area :description
  .subboard_submit
    = form.submit

app/views/subboards/show.html.haml
%h1
  = @subboard.name
%p
  = @subboard.description

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign Up" %>
  </div>
<% end %>